### ISSUE TITLE
Test Carousel Browse functionality

### ISSUE THREAD

**Issue by matthewjmckinley** [omeka-s-modules/ItemCarouselBlock#1]
Please test:
- adding/removing/re-ordering items with thumbnails of different size and shape
- adding titles and captions of various lengths
- with a test set of various size images/captions, adjusting each of the settings on their own and together
- all of the above in chrome/firefox/IE (Safari if possible, though I've already tested pretty thoroughly)

Let me know if anything looks broken or weird! Also open to feedback on user-friendliness or any confusion on the design or function of the settings. Thanks!

**Comment by georgiawebgurl** [comment]
Tested: Default Theme, Cozy, Center Row, Papers, The Daily - Chrome, Firefox, Edge 
Thoughts thus far:
- Default without much monkeying with settings worked well. 
- Easy to break especially with the carousel settings for fade between slides, items per page, slide padding, & stretch image to fill slide. 
- More helper text and possibly min/max or default values in helper text (so that if someone messes up a setting, it is easy to change back to the default). Documentation will help, too, in terms of best practices for text. 

This needs testing in Safari, IOS if someone can do that. Matthew has my list of tests and results.

**Comment by sharonmleon** [comment]
Admin notes:
- In the admin interface, the helper text needs some consistency about punctuation. Some text has a period. Some text does not. 
- I agree that the helper text will need some work. There isn't much space, but without documentation, not much of it is helpful to me as someone who does not mess much with CSS.
- On slide options, I'm not sure that I'd call those all Thumbnails. The first one, i.e. large is a full-sized image, and then the next two are thumbnails. The introduction of the term medium is not something we use in other places. It's more a case of rectangle or square. 

Public view (Firefox on a Mac):
- Bad things happen when you try to float the text on a thumbnail.) 
![Screen Shot 2021-03-12 at 15 31 26](https://user-images.githubusercontent.com/741480/110996820-7fcea600-834a-11eb-9503-89f11d4ee7e3.png)
- And it seems like the item title can stack rather than wrap when it is longer than the width of the media.
![Screen Shot 2021-03-12 at 15 35 20](https://user-images.githubusercontent.com/741480/110995835-fbc7ee80-8348-11eb-9057-97b8b8591597.png)
- Same stacking of text happens in Safari.
- Could be user error?
<img width="793" alt="settings" src="https://user-images.githubusercontent.com/741480/110996845-8bba6800-834a-11eb-854d-2ea004b6b733.png">

**Comment by matthewjmckinley** [comment]
- Happy to change the helper text, but maybe we should re-examine after Robin writes up the documentation, so we can see how they would work together and how much/little we need to include as helper text. Will also standardize punctuation at that point.
- Would 'Image Type' work? And the selections (large, medium, square) come directly from the `blockThumbnailTypeSelect` helper, I'm not setting them within the form https://omeka.org/s/docs/developer/modules/page_blocks/#form
- Hm, I'm not able to replicate that text stacking bug on either Firefox or Safari with the same settings:
<img width="1419" alt="Screen Shot 2021-03-12 at 1 58 06 PM" src="https://user-images.githubusercontent.com/69479529/111003027-36c32580-833b-11eb-82f5-5742a67c0694.png">
<img width="1463" alt="Screen Shot 2021-03-12 at 1 59 25 PM" src="https://user-images.githubusercontent.com/69479529/111003036-3aef4300-833b-11eb-9214-88be3d76525a.png">

**Comment by sharonmleon** [comment]
So on the thumbnail language issues, that does appear to be the system. I apologize. The language from Classic is blurring into my reading. So, that might be something that we need to think about changing system-wide. In most places in S, we talk about media and thumbnails.

**Comment by georgiawebgurl** [comment]
Updated testing from 3/20-3/25: Detailed comments & screenshots here: [(https://docs.google.com/document/d/18i5auSbw5r-NbhblDWNpaw7zE9ocOyrtu0OSMFowM5I/edit#heading=h.s3u2sx1yv9aj)]

**Comment by georgiawebgurl** [comment]
I will run through my carousels in Edge and Android later today. We will still need some testing on IOS. Great progress overall and the layout / choices are much improved.

**Comment by georgiawebgurl** [comment]
Google doc updated with testing in Edge and Android 11.

**Comment by georgiawebgurl** [comment]
Documentation in progress for this module.

**Comment by sharonmleon** [comment]
Branch for documentation: https://github.com/omeka/omeka-s-enduser/tree/carousel-browse

**Comment by sharonmleon** [comment]
@matthewjmckinley Would you please check on the first draft of the documentation, which is available in the branch linked above.

**Comment by matthewjmckinley** [comment]
Only added some small typo and wording suggestions. Looks great overall!

**Comment by sharonmleon** [comment]
Great. Thank you. If you work with me long enough, you'll find out that typos are endemic. 

One more outstanding issue, and then we should be able to head to release.
