### ISSUE TITLE
When multiple carousel on the same page, first carousel settings apply to others

### ISSUE THREAD

**Issue by coolidfrez** [omeka-s-modules/ItemCarouselBlock#15]
Hi and thank you for this module.

We have a strange problem using the carousel module.
If several carousels apply to the same page, the settings of the first apply to the other carousels. for example the "item per slide" parameter is set at 2 items for the first and 3 items for the second but all carousels display 2 items.

A big thank you to you !

**Comment by matthewjmckinley** [comment]
Hi, thanks for catching this! The CSS customizations that happen when Item Carousel Block options are applied were not previously differentiating between multiple carousel blocks--hence, any changes applied to one would be applied to all.

This has been fixed in the latest commit. After testing this and a few other behind-the-scene updates, we'll be releasing a new version of the module in the next few weeks. I will drop back in and let you know when it is released. Thanks again!

**Comment by matthewjmckinley** [comment]
Fixed in https://github.com/omeka-s-modules/ItemCarouselBlock/commit/63e054059f13430589c91a71cbf6a3c2e92a6ce8 and added latest release
