### ISSUE TITLE
Invalid Module.php file

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/ItemCarouselBlock#8]
Error in Module admin interface after pulling most recent changes.

**Comment by matthewjmckinley** [comment]
I think this is because I changed the namespace _again_ after group discussion of the best name back in March. https://github.com/omeka-s-modules/ItemCarouselBlock/commit/a44c49007be4228c5a5790ad3133d265fbbe1966 
@sharonmleon could you try changing your local module directory name to `ItemCarouselBlock`?

**Comment by sharonmleon** [comment]
That seems to have done it.
